In [5]:
import numpy as np
import pandas as pd
import statistics

In [2]:
df = pd.read_csv("wide_dataset.csv")
df

,Farm_ID,District,Location,Year,June,July,Aug,Sept,Oct
0,R1,Raichur,Turvihal,2018.0,0.194397,0.313071,0.431746,0.550420,0.592331
1,R1,Raichur,Turvihal,2019.0,0.139217,0.044806,0.207262,0.369719,0.534465
2,R1,Raichur,Turvihal,2020.0,0.399280,0.428845,0.458411,0.487977,0.670100
3,R1,Raichur,Turvihal,2021.0,0.315583,0.322194,0.328805,0.648679,0.663072
4,R10,Raichur,Ballatgi,2018.0,0.116623,0.083705,0.050787,0.150787,0.413716
...,...,...,...,...,...,...,...,...,...
75,R8,Raichur,Amareshwara Camp,2021.0,0.116953,0.134947,0.152940,0.444814,0.633293
76,R9,Raichur,Hiredinni,2018.0,0.132740,0.200240,0.267739,0.335238,0.491843
77,R9,Raichur,Hiredinni,2019.0,0.084859,0.058172,0.094926,0.131679,0.233903
78,R9,Raichur,Hiredinni,2020.0,0.108032,0.240275,0.372518,0.504761,0.611738
79,R9,Raichur,Hiredinni,2021.0,0.158301,0.247561,0.336821,0.622122,0.618344

In [8]:
df["Seasonal_mean"] = df[["June", "July", "Aug", "Sept", "Oct"]].mean(axis=1)
df

,Farm_ID,District,Location,Year,June,July,Aug,Sept,Oct,Seasonal_mean
0,R1,Raichur,Turvihal,2018.0,0.194397,0.313071,0.431746,0.550420,0.592331,0.416393
1,R1,Raichur,Turvihal,2019.0,0.139217,0.044806,0.207262,0.369719,0.534465,0.259094
2,R1,Raichur,Turvihal,2020.0,0.399280,0.428845,0.458411,0.487977,0.670100,0.488922
3,R1,Raichur,Turvihal,2021.0,0.315583,0.322194,0.328805,0.648679,0.663072,0.455667
4,R10,Raichur,Ballatgi,2018.0,0.116623,0.083705,0.050787,0.150787,0.413716,0.163124
...,...,...,...,...,...,...,...,...,...,...
75,R8,Raichur,Amareshwara Camp,2021.0,0.116953,0.134947,0.152940,0.444814,0.633293,0.296589
76,R9,Raichur,Hiredinni,2018.0,0.132740,0.200240,0.267739,0.335238,0.491843,0.285560
77,R9,Raichur,Hiredinni,2019.0,0.084859,0.058172,0.094926,0.131679,0.233903,0.120708
78,R9,Raichur,Hiredinni,2020.0,0.108032,0.240275,0.372518,0.504761,0.611738,0.367465
79,R9,Raichur,Hiredinni,2021.0,0.158301,0.247561,0.336821,0.622122,0.618344,0.396630

In [9]:
df["Seasonal_max"] = df[["June", "July", "Aug", "Sept", "Oct"]].max(axis=1)
df

,Farm_ID,District,Location,Year,June,July,Aug,Sept,Oct,Seasonal_mean,Seasonal_max
0,R1,Raichur,Turvihal,2018.0,0.194397,0.313071,0.431746,0.550420,0.592331,0.416393,0.592331
1,R1,Raichur,Turvihal,2019.0,0.139217,0.044806,0.207262,0.369719,0.534465,0.259094,0.534465
2,R1,Raichur,Turvihal,2020.0,0.399280,0.428845,0.458411,0.487977,0.670100,0.488922,0.670100
3,R1,Raichur,Turvihal,2021.0,0.315583,0.322194,0.328805,0.648679,0.663072,0.455667,0.663072
4,R10,Raichur,Ballatgi,2018.0,0.116623,0.083705,0.050787,0.150787,0.413716,0.163124,0.413716
...,...,...,...,...,...,...,...,...,...,...,...
75,R8,Raichur,Amareshwara Camp,2021.0,0.116953,0.134947,0.152940,0.444814,0.633293,0.296589,0.633293
76,R9,Raichur,Hiredinni,2018.0,0.132740,0.200240,0.267739,0.335238,0.491843,0.285560,0.491843
77,R9,Raichur,Hiredinni,2019.0,0.084859,0.058172,0.094926,0.131679,0.233903,0.120708,0.233903
78,R9,Raichur,Hiredinni,2020.0,0.108032,0.240275,0.372518,0.504761,0.611738,0.367465,0.611738
79,R9,Raichur,Hiredinni,2021.0,0.158301,0.247561,0.336821,0.622122,0.618344,0.396630,0.622122

In [10]:
df["Growth_rate"] = df["Sept"] - df["June"]

In [11]:
df

,Farm_ID,District,Location,Year,June,July,Aug,Sept,Oct,Seasonal_mean,Seasonal_max,Growth_rate
0,R1,Raichur,Turvihal,2018.0,0.194397,0.313071,0.431746,0.550420,0.592331,0.416393,0.592331,0.397934
1,R1,Raichur,Turvihal,2019.0,0.139217,0.044806,0.207262,0.369719,0.534465,0.259094,0.534465,0.395248
2,R1,Raichur,Turvihal,2020.0,0.399280,0.428845,0.458411,0.487977,0.670100,0.488922,0.670100,0.270821
3,R1,Raichur,Turvihal,2021.0,0.315583,0.322194,0.328805,0.648679,0.663072,0.455667,0.663072,0.347488
4,R10,Raichur,Ballatgi,2018.0,0.116623,0.083705,0.050787,0.150787,0.413716,0.163124,0.413716,0.297092
...,...,...,...,...,...,...,...,...,...,...,...,...
75,R8,Raichur,Amareshwara Camp,2021.0,0.116953,0.134947,0.152940,0.444814,0.633293,0.296589,0.633293,0.516341
76,R9,Raichur,Hiredinni,2018.0,0.132740,0.200240,0.267739,0.335238,0.491843,0.285560,0.491843,0.359102
77,R9,Raichur,Hiredinni,2019.0,0.084859,0.058172,0.094926,0.131679,0.233903,0.120708,0.233903,0.149044
78,R9,Raichur,Hiredinni,2020.0,0.108032,0.240275,0.372518,0.504761,0.611738,0.367465,0.611738,0.503705
79,R9,Raichur,Hiredinni,2021.0,0.158301,0.247561,0.336821,0.622122,0.618344,0.396630,0.622122,0.460043

In [12]:
df["NDVI_range"] = df["Seasonal_max"] - df[["June", "July", "Aug", "Sept", "Oct"]].min(axis=1)

In [13]:
df

,Farm_ID,District,Location,Year,June,July,Aug,Sept,Oct,Seasonal_mean,Seasonal_max,Growth_rate,NDVI_range
0,R1,Raichur,Turvihal,2018.0,0.194397,0.313071,0.431746,0.550420,0.592331,0.416393,0.592331,0.397934,0.397934
1,R1,Raichur,Turvihal,2019.0,0.139217,0.044806,0.207262,0.369719,0.534465,0.259094,0.534465,0.395248,0.489659
2,R1,Raichur,Turvihal,2020.0,0.399280,0.428845,0.458411,0.487977,0.670100,0.488922,0.670100,0.270821,0.270821
3,R1,Raichur,Turvihal,2021.0,0.315583,0.322194,0.328805,0.648679,0.663072,0.455667,0.663072,0.347488,0.347488
4,R10,Raichur,Ballatgi,2018.0,0.116623,0.083705,0.050787,0.150787,0.413716,0.163124,0.413716,0.297092,0.362929
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,R8,Raichur,Amareshwara Camp,2021.0,0.116953,0.134947,0.152940,0.444814,0.633293,0.296589,0.633293,0.516341,0.516341
76,R9,Raichur,Hiredinni,2018.0,0.132740,0.200240,0.267739,0.335238,0.491843,0.285560,0.491843,0.359102,0.359102
77,R9,Raichur,Hiredinni,2019.0,0.084859,0.058172,0.094926,0.131679,0.233903,0.120708,0.233903,0.149044,0.175730
78,R9,Raichur,Hiredinni,2020.0,0.108032,0.240275,0.372518,0.504761,0.611738,0.367465,0.611738,0.503705,0.503705
79,R9,Raichur,Hiredinni,2021.0,0.158301,0.247561,0.336821,0.622122,0.618344,0.396630,0.622122,0.460043,0.463821

In [21]:
def classify_crop_health(ndvi):
    if ndvi >= 0.33:
        return "Healthy"
    elif ndvi >= 0.18:
        return "Moderate"
    else:
        return "Stressed"

df["Crop_health"] = df["Seasonal_mean"].apply(classify_crop_health)

In [22]:
df

,Farm_ID,District,Location,Year,June,July,Aug,Sept,Oct,Seasonal_mean,Seasonal_max,Growth_rate,NDVI_range,Crop_health
0,R1,Raichur,Turvihal,2018.0,0.194397,0.313071,0.431746,0.550420,0.592331,0.416393,0.592331,0.397934,0.397934,Healthy
1,R1,Raichur,Turvihal,2019.0,0.139217,0.044806,0.207262,0.369719,0.534465,0.259094,0.534465,0.395248,0.489659,Moderate
2,R1,Raichur,Turvihal,2020.0,0.399280,0.428845,0.458411,0.487977,0.670100,0.488922,0.670100,0.270821,0.270821,Healthy
3,R1,Raichur,Turvihal,2021.0,0.315583,0.322194,0.328805,0.648679,0.663072,0.455667,0.663072,0.347488,0.347488,Healthy
4,R10,Raichur,Ballatgi,2018.0,0.116623,0.083705,0.050787,0.150787,0.413716,0.163124,0.413716,0.297092,0.362929,Stressed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,R8,Raichur,Amareshwara Camp,2021.0,0.116953,0.134947,0.152940,0.444814,0.633293,0.296589,0.633293,0.516341,0.516341,Moderate
76,R9,Raichur,Hiredinni,2018.0,0.132740,0.200240,0.267739,0.335238,0.491843,0.285560,0.491843,0.359102,0.359102,Moderate
77,R9,Raichur,Hiredinni,2019.0,0.084859,0.058172,0.094926,0.131679,0.233903,0.120708,0.233903,0.149044,0.175730,Stressed
78,R9,Raichur,Hiredinni,2020.0,0.108032,0.240275,0.372518,0.504761,0.611738,0.367465,0.611738,0.503705,0.503705,Healthy
79,R9,Raichur,Hiredinni,2021.0,0.158301,0.247561,0.336821,0.622122,0.618344,0.396630,0.622122,0.460043,0.463821,Healthy

In [23]:
df["Crop_health"].value_counts()

Crop_health
Moderate    41
Healthy     20
Stressed    19
Name: count, dtype: int64

In [24]:
df.describe()

,Year,June,July,Aug,Sept,Oct,Seasonal_mean,Seasonal_max,Growth_rate,NDVI_range
count,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000
mean,2019.500000,0.137530,0.170718,0.224160,0.338078,0.435362,0.261169,0.448386,0.297831,0.327041
std,1.125088,0.070151,0.101159,0.133156,0.164244,0.156513,0.106406,0.153662,0.136748,0.125826
min,2018.000000,0.034539,0.034057,0.000000,0.067244,0.131377,0.076864,0.131377,0.039529,0.066135
25%,2018.750000,0.096243,0.074499,0.117555,0.188290,0.325776,0.183287,0.346521,0.196213,0.252300
50%,2019.500000,0.120358,0.161573,0.216141,0.343121,0.431311,0.261122,0.463458,0.297912,0.340359
75%,2020.250000,0.159651,0.242097,0.328067,0.463081,0.565604,0.328655,0.565604,0.407984,0.435995
max,2021.000000,0.399280,0.428845,0.522020,0.668945,0.685243,0.493596,0.685243,0.533993,0.533993

In [29]:
df.to_csv("final_dataset.csv", index=False)